#start
steps:
  # Build the unified container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:latest'
      - '.'
    id: 'build-image'

  # Push the image (SHORT SHA tag)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:$SHORT_SHA']
    id: 'push-sha'
    waitFor: ['build-image']

  # Push the image (latest tag)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:latest']
    id: 'push-latest'
    waitFor: ['build-image']

images:
  - 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/recon-489807/recon-repo/recon-pms:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
